const GOOGLE_FORM_APPLY_LINK = 'https://forms.gle/PMPbLPy3doWVhSC8A';

export const JOBS = [
  {
    id: '3109165690',
    link: GOOGLE_FORM_APPLY_LINK,
    title: 'Sr. Unity Developer',
    location: 'United States (Remote)',
    aboutTheRole: `We are seeking a developer responsible for building games within the Unity game engine. Your primary responsibilities will be to implement game functionality translating design ideas, concepts, and requirements into a functional and engaging game. You will be building out play-and-earn games that target a global audience of players. Our team has a strong track record building games at the world's largest traditional gaming companies and is passionate about Web3 and GameFi.`,
    responsibilities: [
      'Design, implement, and test game features independently and in teams using Unity (C#).',
      `Assist in defining a project's scope, objectives, and design specifications.`,
      'Plan, develop, and implement large-scale complex projects from conception to completion.',
      'Understand and evaluate complex data models.',
      'Improve the maintainability of our games, including refactoring code during implementation.',
      'Develop and maintain documentation.',
      'Participate in code reviews. Follow best practices, and help team members improve.',
    ],
    requirements: [
      'Be able to design, develop and deploy major in-game features from start to finish.',
      'Have developed and shipped games made with Unity game engine.',
      'Knowledge expert in areas of applications, software architecture, and infrastructure.',
      'Basic understanding of Agile processes (although we are a small, scrappy team, so don’t run scrum by the books just yet).',
      'Knowledgeable in TDD and CI/CD.',
      'A great team member, capable of mentoring other engineers.',
      'We are a growing distributed team that embraces remote work.',
      'Interest in blockchain, blockchain development, and a decentralized economy model.',
      'Love for Web3 and ideally games!',
    ],
    benefits: [
      'Competitive salary',
      'Fully remote and async work',
      'Annual PTO and paid holidays',
      'Company health plan including dental',
      '401k',
    ],
  },
  {
    id: '3109168449',
    link: GOOGLE_FORM_APPLY_LINK,
    title: 'Sr. Backend Developer',
    location: 'United States (Remote)',
    aboutTheRole: `We are seeking a senior developer with full-stack skills and a strong passion for working on blockchain products built with Solidity. You will be expected to take full ownership of the full tech stack and be comfortable working independently and remotely. Your primary responsibilities will be to implement Web3 functionality translating design ideas, concepts, and requirements into a functional and engaging website and product experience. Our team has a strong track record building games at the world's largest traditional gaming companies and is passionate about Web3 and GameFi.`,
    responsibilities: undefined,
    requirements: [
      '6 years of relevant work experience, including in a high-volume or critical production service environment',
      'Knowledge of AWS or Google Cloud',
      'Knowledge of C# and/or Python. Knowing both is ideal but one is sufficient if you are happy to learn the other',
      'Experience building and running distributed systems development and service-oriented architectures',
      'A proven ability to analyze requirements and make corresponding design decisions',
      'Experience with at least one major NoSQL database. Preferably at large scale',
      'Experience working at scale',
    ],
    benefits: [
      'Competitive salary',
      'Fully remote and async work',
      'Annual PTO and paid holidays',
      'Company health plan including dental',
      '401k',
    ],
  },
  {
    id: '3109562681',
    link: GOOGLE_FORM_APPLY_LINK,
    title: 'Head Of Marketing',
    location: 'United States (Remote)',
    aboutTheRole: `As the Head of Marketing for Nifty League, you will be responsible for shaping and implementing a crypto-native growth marketing strategy to grow our player community (both crypto and non-crypto) and deepen their engagement in the Nifty League ecosystem. While running traditional paid acquisition and PR campaigns is fine, you should thrive when developing and implementing growth experiments that capitalize on the natural growth strategies that web3 gives us. You will collaborate highly with other teams regularly including Product, Community, and Art.`,
    responsibilities: [
      'Think strategically from a crypto-native perspective to pitch and implement new growth strategies, managing user acquisition, retention, and funnel optimization',
      'Brainstorm and execute viral growth strategies and referral programs, utilizing analytics to make data-informed decisions on when and how to iterate',
      'Design brand strategy and messaging across all PR channels to drive awareness of Nifty Smashers and other Nifty League games',
      'Leverage our Club (guild) partners to publish and capitalize on content creation and competitive gameplay within their player ecosystems',
      'Develop and operationalize content for Tik Tok, Instagram, Twitch, and Youtube',
      'Generating interest for our founders and management on top web3/tech podcasts, and blog/newsletter content features',
      'Work closely with the Nifty League founders and investor teams in designing an effective PR strategy and assist in managing those press and media channel relationships',
      'Collaborate with Game and Product teams to develop a roadmap of growth projects that are tied to clear goals and measurable metrics',
      'Develop a deep understanding of different player segments: their problems, their needs, their desires, and translate all of this into exceptional player experiences',
      'Stay up-to-date on the blockchain gaming ecosystem and the efficacy of different growth strategies employed by different blockchain gaming studios',
    ],
    requirements: [
      '5+ years of experience in PR or growth marketing, ideally in the gaming space',
      'Must be passionate about games and the interaction of blockchain and gaming',
      'Great interpersonal, relationship management, and communication skills',
      'Deep understanding of the variety of growth strategies employed by free-to-play gaming companies, crypto companies, and blockchain gaming companies',
      'Excellent written, verbal, and interpersonal communication skills',
    ],
    benefits: [
      'Competitive salary',
      'Fully remote and async work',
      'Annual PTO and paid holidays',
      'Company health plan including dental',
      '401k',
    ],
  },
];
